Added exit error to workflow

diff --git a/.github/workflows/demo_workflow.yml b/.github/workflows/demo_workflow.yml
--- a/.github/workflows/demo_workflow.yml
+++ b/.github/workflows/demo_workflow.yml
@@ -30,3 +30,7 @@ jobs:
         run: |
           echo "The first secret is below"
           echo "${{ secrets.XKEY }}"
+      - name: Actions error
+        run: |
+          echo "::error::Filename doesn't match possible files"
+          exit 1
